minimal change to setup to work with Docker images rather than bind mounts

diff --git a/bin/moodle-docker-compose b/bin/moodle-docker-compose
--- a/bin/moodle-docker-compose
+++ b/bin/moodle-docker-compose
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
 set -e
 
-if [ ! -d "$MOODLE_DOCKER_WWWROOT" ];
-then
-    echo 'Error: $MOODLE_DOCKER_WWWROOT is not set or not an existing directory'
-    exit 1
-fi
+# if [ ! -d "$MOODLE_DOCKER_WWWROOT" ];
+# then
+#     echo 'Error: $MOODLE_DOCKER_WWWROOT is not set or not an existing directory'
+#     exit 1
+# fi
 
 if [ -z "$MOODLE_DOCKER_DB" ];
 then
